'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';

type Mode = 'login' | 'request';
export function AuthFlow({ mode }: { mode: Mode }) {
  const router = useRouter(); const [mobile, setMobile] = useState(''); const [sent, setSent] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function send(event: FormEvent) { event.preventDefault(); setError(''); const res = await fetch('/api/v1/auth/otp', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ mobile }) }); const data = await res.json(); if (!res.ok) return setError(data.error ?? 'ارسال رمز ناموفق بود.'); setSent(true); setMessage('رمز ارسال شد. در محیط آزمایشی آن را در صندوق پایین صفحه ببینید.'); }
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const code = new FormData(event.currentTarget).get('code'); const res = await fetch('/api/v1/auth/verify', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ mobile, code, idempotencyKey: crypto.randomUUID() }) }); const data = await res.json(); if (!res.ok) return setError(data.error ?? 'تأیید رمز ناموفق بود.'); router.push(data.onboardingRequired ? `/request?onboarding=1` : mode === 'request' ? '/request?new=1' : '/account'); }
  return <div className="card">{!sent ? <form className="form" onSubmit={send}><label className="field">شماره همراه ایران<input value={mobile} onChange={(event) => setMobile(event.target.value)} inputMode="tel" autoComplete="tel" required placeholder="۰۹۱۲۱۲۳۴۵۶۷" /><span className="hint">ورود و عضویت بدون رمز عبور دائمی انجام می‌شود.</span></label>{error ? <p className="error" role="alert">{error}</p> : null}<button className="button button-primary" type="submit">دریافت رمز یک‌بارمصرف</button></form> : <form className="form" onSubmit={verify}><p className="success" role="status">{message}</p><label className="field">رمز ۶ رقمی<input name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} required /></label>{error ? <p className="error" role="alert">{error}</p> : null}<button className="button button-primary" type="submit">تأیید و ادامه</button><button className="button button-secondary" type="button" onClick={() => setSent(false)}>ویرایش شماره</button></form>}</div>;
}
