'use client';
import { useEffect, useState, type FormEvent } from 'react';

type Entry = { slug: string; title: string; state: string; version: number; isPlaceholder: boolean; updatedAt: string };
export function ContentManager() {
  const [entries, setEntries] = useState<Entry[]>([]); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const reload = () => fetch('/api/v1/admin/content').then(async (response) => { if (!response.ok) throw new Error((await response.json()).error); setEntries(await response.json()); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'دسترسی ممکن نیست.'));
  useEffect(() => { reload(); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); const slug = String(form.get('slug')); const response = await fetch(`/api/v1/admin/content/${slug}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ title: form.get('title'), body: { content: form.get('body') }, state: form.get('state'), isPlaceholder: form.get('isPlaceholder') === 'on' }) }); if (!response.ok) return setError((await response.json()).error ?? 'ذخیره ناموفق بود.'); setNotice('نسخه جدید ذخیره شد.'); event.currentTarget.reset(); reload(); }
  return <div className="grid-2"><form className="card form" onSubmit={save}><h2>ویرایش یا ایجاد محتوا</h2><label className="field">شناسه صفحه<input name="slug" required pattern="[a-z0-9-]+" placeholder="home-hero" /></label><label className="field">عنوان<input name="title" required /></label><label className="field">متن<textarea name="body" required /></label><label className="field">وضعیت<select name="state" defaultValue="DRAFT"><option value="DRAFT">پیش‌نویس</option><option value="PUBLISHED">منتشرشده</option></select></label><label><input name="isPlaceholder" type="checkbox" /> داده placeholder است و نباید در تولید منتشر شود.</label>{error ? <p className="error" role="alert">{error}</p> : null}{notice ? <p className="success" role="status">{notice}</p> : null}<button className="button button-primary" type="submit">ذخیره نسخه</button></form><section className="card"><h2>نسخه‌های موجود</h2>{entries.length ? <ul>{entries.map((entry) => <li key={entry.slug}><bdi>{entry.slug}</bdi> — {entry.title} — نسخه {entry.version} — {entry.state}{entry.isPlaceholder ? ' — placeholder' : ''}</li>)}</ul> : <p className="muted">محتوایی ثبت نشده است.</p>}</section></div>;
}
