'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api, money, persianDate } from '@/lib/api';
import { Icon } from './Icon';

type OfferDetails = { title: string; description: string; scope: string; deliverable: string; durationMinutes: number; timing: string; expertMix: string; baseAmountIrr: number; taxAmountIrr: number; totalAmountIrr: number; feeDeductionTerms: string; termsVersion: string; cancellationVersion: string };
type Offer = { status: string; validUntil?: string; offer?: OfferDetails; order?: { reference: string; state: string } };

export function OfferFlow({ token }: { token: string }) {
  const [offer, setOffer] = useState<Offer | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'accepted' | 'error'>('loading');
  const [message, setMessage] = useState('');
  const [billingReady, setBillingReady] = useState(false);
  const [emailReady, setEmailReady] = useState(false);
  const [emailRequested, setEmailRequested] = useState(false);
  const [accepted, setAccepted] = useState(false);
  useEffect(() => { api<Offer>(`/api/v1/offers/${token}`).then((data) => { setOffer(data); setState('ready'); }).catch((error) => { setMessage(error.message); setState('error'); }); api<{ profile?: { emailVerifiedAt?: string } }>('/api/v1/account').then((account) => setEmailReady(Boolean(account.profile?.emailVerifiedAt))).catch(() => setEmailReady(false)); }, [token]);
  async function saveBilling(formData: FormData) { try { await api(`/api/v1/offers/${token}/billing`, { method: 'POST', body: JSON.stringify({ legalName: formData.get('legalName'), nationalId: formData.get('nationalId'), billingAddress: formData.get('billingAddress'), postalCode: formData.get('postalCode') || undefined }) }); setBillingReady(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'ثبت اطلاعات صورتحساب ناموفق بود.'); } }
  async function accept() { try { await api(`/api/v1/offers/${token}/accept`, { method: 'POST', body: JSON.stringify({ termsVersion: offer?.offer?.termsVersion, idempotencyKey: crypto.randomUUID() }) }); setState('accepted'); } catch (error) { setMessage(error instanceof Error ? error.message : 'پذیرش پیشنهاد ناموفق بود.'); } }
  async function requestEmail() { try { await api('/api/v1/account/email-verification/request', { method: 'POST', body: '{}' }); setEmailRequested(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'برای تأیید ایمیل ابتدا با حساب مرتبط وارد شوید.'); } }
  async function confirmEmail(formData: FormData) { try { await api('/api/v1/account/email-verification/confirm', { method: 'POST', body: JSON.stringify({ token: formData.get('token') }) }); setEmailReady(true); } catch (error) { setMessage(error instanceof Error ? error.message : 'کد تأیید ایمیل معتبر نیست.'); } }
  if (state === 'loading') return <div className="loading-state" role="status"><span/>در حال اعتبارسنجی لینک خصوصی…</div>;
  if (state === 'error') return <div className="result-state error"><Icon name="warning"/><h2>پیشنهاد قابل دریافت نیست</h2><p>{message}</p></div>;
  if (!offer || ['EXPIRED', 'REVOKED'].includes(offer.status)) return <div className="result-state error"><Icon name="warning"/><h2>این پیشنهاد منقضی یا باطل شده است</h2><p>پرداخت از این لینک ممکن نیست. برای صدور مجدد با تیم عملیات تماس بگیرید.</p></div>;
  if (state === 'accepted' || offer.order) return <div className="result-state success"><Icon name="check"/><h2>پیشنهاد پذیرفته شده است</h2><p>برای انتخاب روش پرداخت ادامه دهید.</p><Link className="button button-large" href={`/pay/${token}`}>ادامه به پرداخت <Icon name="arrow"/></Link></div>;
  const details = offer.offer;
  if (!details) return <div className="result-state error"><Icon name="warning"/><h2>نسخه پیشنهاد در دسترس نیست</h2></div>;
  return <div className="offer-layout"><article className="offer-document"><div className="offer-private"><Icon name="lock"/> پیشنهاد خصوصی و مخصوص همین درخواست</div><h2>{details.title}</h2><p>{details.description}</p><dl className="offer-facts"><div><dt>دامنه</dt><dd>{details.scope}</dd></div><div><dt>خروجی</dt><dd>{details.deliverable}</dd></div><div><dt>مدت</dt><dd>{new Intl.NumberFormat('fa-IR').format(details.durationMinutes)} دقیقه</dd></div><div><dt>زمان‌بندی</dt><dd>{details.timing}</dd></div><div><dt>ترکیب تخصص</dt><dd>{details.expertMix}</dd></div><div><dt>اعتبار تا</dt><dd>{offer.validUntil && persianDate(offer.validUntil)}</dd></div></dl><section className="offer-terms"><h3>مرز تعهد و شرایط</h3><p>{details.feeDeductionTerms}</p><p>این ارزیابی و خروجی مقدماتی جایگزین حسابرسی، نظر حقوقی یا گزارش رسمی تخصصی نیست و قرارداد پروژه اصلی مستقل خواهد بود.</p><div><Link href="/terms">شرایط استفاده — {details.termsVersion}</Link><Link href="/cancellation">لغو و استرداد — {details.cancellationVersion}</Link></div></section></article><aside className="offer-checkout"><h2>خلاصه مبلغ</h2><dl className="money-table"><div><dt>مبلغ پایه</dt><dd>{money(details.baseAmountIrr)}</dd></div><div><dt>مالیات و عوارض</dt><dd>{money(details.taxAmountIrr)}</dd></div><div className="total"><dt>مبلغ نهایی</dt><dd>{money(details.totalAmountIrr)}</dd></div></dl>{!billingReady ? <form action={saveBilling}><h3>اطلاعات صورتحساب سازمان</h3><label>نام ثبتی<input name="legalName" required minLength={2}/></label><label>شناسه ملی<input name="nationalId" required inputMode="numeric" pattern="[0-9]{11}" dir="ltr"/></label><label>نشانی صورتحساب<textarea name="billingAddress" rows={3} minLength={10} required/></label><label>کد پستی <span>(اختیاری)</span><input name="postalCode" inputMode="numeric" pattern="[0-9]{10}" dir="ltr"/></label><button className="button">ثبت اطلاعات صورتحساب</button></form> : !emailReady ? <div className="email-check"><h3>تأیید ایمیل نماینده</h3><p>پیش از پذیرش نخستین سفارش، ایمیل حساب مرتبط باید تأیید شود.</p>{!emailRequested ? <><button className="button" onClick={requestEmail}>ارسال لینک تأیید</button><Link className="secondary-action" href={`/login?next=/offer/${token}`}>ورود با حساب مرتبط</Link></> : <form action={confirmEmail}><label>توکن تأیید ایمیل<input name="token" dir="ltr" required/></label><button className="button">تأیید ایمیل</button></form>}</div> : <><label className="check-field"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)}/><span>مبلغ، خروجی، شرایط و نسخه اسناد را خوانده‌ام و می‌پذیرم.</span></label><button className="button button-large" disabled={!accepted} onClick={accept}>پذیرش پیشنهاد <Icon name="arrow"/></button></>}{message && <p className="form-error" role="alert">{message}</p>}</aside></div>;
}
